"""categorias zona claves foraneas

Revision ID: 06d6c28e0b06
Revises: 5f2f16cc96a6
Create Date: 2025-01-27 07:52:42.277248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d6c28e0b06'
down_revision: Union[str, None] = '5f2f16cc96a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
