"""Crear tablas de locales23

Revision ID: 2e6ad76bb049
Revises: 1f374a6d7061
Create Date: 2025-01-23 16:26:30.451309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6ad76bb049'
down_revision: Union[str, None] = '1f374a6d7061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
