"""Migración

Revision ID: 2f95e5d8bcb7
Revises: b59ff17de3df
Create Date: 2025-01-24 05:41:44.513590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f95e5d8bcb7'
down_revision: Union[str, None] = 'b59ff17de3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas', sa.Column('categoria_nombre', sa.String(length=100), nullable=False))
    op.drop_constraint('FK__zonas__categoria__5070F446', 'zonas', type_='foreignkey')
    op.create_foreign_key('fk_zona_categoria', 'zonas', 'categorias', ['categoria_nombre'], ['nombre'])
    op.drop_column('zonas', 'categoria_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_zona_categoria', 'zonas', type_='foreignkey')
    op.create_foreign_key('FK__zonas__categoria__5070F446', 'zonas', 'categorias', ['categoria_id'], ['id'])
    op.drop_column('zonas', 'categoria_nombre')
    # ### end Alembic commands ###
