"""Agregar tabla Users

Revision ID: 367b46d4758b
Revises: e8b70d5746e6
Create Date: 2025-01-21 17:36:40.760417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367b46d4758b'
down_revision: Union[str, None] = 'e8b70d5746e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
