"""Crear tablas de locales

Revision ID: 40b53a966a25
Revises: 7c3fd0d66868
Create Date: 2025-01-23 16:04:36.186329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b53a966a25'
down_revision: Union[str, None] = '7c3fd0d66868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
