"""categorias zona 

Revision ID: 5f2f16cc96a6
Revises: 6e045722d8d1
Create Date: 2025-01-27 07:41:06.694085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2f16cc96a6'
down_revision: Union[str, None] = '6e045722d8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zonas', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'zonas', 'categorias', ['categoria_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zonas', type_='foreignkey')
    op.drop_column('zonas', 'categoria_id')
    # ### end Alembic commands ###
