"""Actualizar esquema de la base de datos

Revision ID: ea274f75395c
Revises: b1fb170b0312
Create Date: 2025-01-20 18:01:14.648211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea274f75395c'
down_revision: Union[str, None] = 'b1fb170b0312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
